language: php
php:
  - 5.4
  - 5.3

script: phpunit --configuration phpunit.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net##addshore"
    on_success: change
    on_failure: always